name: CI

on:

  push:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/rf-mlflow-notebook
    steps:
      
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Setting up MLflow 
        run: pip install mlflow==2.22.0

      - name: Downloading model from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/Enzo-Riviere/mlflow_daghub.mlflow
        run: |
          mkdir -p models/rf_model
          mlflow artifacts download \
            --run-id 52217afce9fe422fb7db7fff9028d857 \
            --artifact-path model/rf_model.pkl \
            --dst-path /


      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Logging in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Building the image
        run: |
          docker build -t $IMAGE_NAME:application_mlflow .

      - name: Pushing images to Docker Hub
        run: |
          docker push $IMAGE_NAME:application_mlflow
